<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit\Scenario\PBList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.Scenario.List.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.Scenario scenarios = 1;</code>
     */
    private $scenarios;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\Scenario[]|\Google\Protobuf\Internal\RepeatedField $scenarios
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAgentSimulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.Scenario scenarios = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScenarios()
    {
        return $this->scenarios;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.Scenario scenarios = 1;</code>
     * @param \Livekit\Scenario[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScenarios($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\Scenario::class);
        $this->scenarios = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Response::class, \Livekit\Scenario_List_Response::class);

