name: livekit-server-sdk-php
env_file:
  - .env
services:
  appserver:
    api: 3
    type: lando
    services:
      image: php:8.1-apache
      command: docker-php-entrypoint apache2-foreground
    build_as_root:
      - apt-get update && apt-get install -y jq
      - curl -sSL https://get.livekit.io/cli | bash
    overrides:
      environment:
        # Support debugging CLI with Xdebug.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
tooling:
  test:
    service: appserver
    cmd:
      - vendor/bin/phpunit --testdox
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
  lk:
    service: appserver
    cmd:
      - lk
  create-test-room:
    service: appserver
    cmd:
      - lk room create testRoomParticipants
  delete-test-room:
    service: appserver
    cmd:
      - lk room delete testRoomParticipants
  start-test-users:
    service: appserver
    cmd:
      - lk load-test --room testRoomParticipants --video-publishers 3 --audio-publishers 5
