<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT! (protoc-gen-twirp_php 0.15.0)
# source: livekit_agent_simulation.proto

declare(strict_types=1);

namespace Livekit;

/**
 *
 *
 * Generated from protobuf service <code>livekit.AgentSimulation</code>
 */
interface AgentSimulation
{
    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateSimulationRun(array $ctx, \Livekit\SimulationRun\Create\Request $req): \Livekit\SimulationRun\Create\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ConfirmSimulationSourceUpload</code>
     *
     * @throws \Twirp\Error
     */
    public function ConfirmSimulationSourceUpload(array $ctx, \Livekit\SimulationRun\ConfirmSourceUpload\Request $req): \Livekit\SimulationRun\ConfirmSourceUpload\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/GetSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function GetSimulationRun(array $ctx, \Livekit\SimulationRun\Get\Request $req): \Livekit\SimulationRun\Get\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ListSimulationRuns</code>
     *
     * @throws \Twirp\Error
     */
    public function ListSimulationRuns(array $ctx, \Livekit\SimulationRun\PBList\Request $req): \Livekit\SimulationRun\PBList\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CancelSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function CancelSimulationRun(array $ctx, \Livekit\SimulationRun\Cancel\Request $req): \Livekit\SimulationRun\Cancel\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateScenario</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateScenario(array $ctx, \Livekit\Scenario\Create\Request $req): \Livekit\Scenario\Create\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateScenarioFromSession</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateScenarioFromSession(array $ctx, \Livekit\Scenario\CreateFromSession\Request $req): \Livekit\Scenario\CreateFromSession\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/DeleteScenario</code>
     *
     * @throws \Twirp\Error
     */
    public function DeleteScenario(array $ctx, \Livekit\Scenario\Delete\Request $req): \Livekit\Scenario\Delete\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/UpdateScenario</code>
     *
     * @throws \Twirp\Error
     */
    public function UpdateScenario(array $ctx, \Livekit\Scenario\Update\Request $req): \Livekit\Scenario\Update\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateScenarioGroup</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateScenarioGroup(array $ctx, \Livekit\ScenarioGroup\Create\Request $req): \Livekit\ScenarioGroup\Create\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/DeleteScenarioGroup</code>
     *
     * @throws \Twirp\Error
     */
    public function DeleteScenarioGroup(array $ctx, \Livekit\ScenarioGroup\Delete\Request $req): \Livekit\ScenarioGroup\Delete\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ListScenarioGroups</code>
     *
     * @throws \Twirp\Error
     */
    public function ListScenarioGroups(array $ctx, \Livekit\ScenarioGroup\PBList\Request $req): \Livekit\ScenarioGroup\PBList\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ListScenarios</code>
     *
     * @throws \Twirp\Error
     */
    public function ListScenarios(array $ctx, \Livekit\Scenario\PBList\Request $req): \Livekit\Scenario\PBList\Response;
}
