<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_analytics.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.AnalyticsStats</code>
 */
class AnalyticsStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.AnalyticsStat stats = 1;</code>
     */
    private $stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Livekit\AnalyticsStat>|\Google\Protobuf\Internal\RepeatedField $stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAnalytics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AnalyticsStat stats = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AnalyticsStat stats = 1;</code>
     * @param array<\Livekit\AnalyticsStat>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\AnalyticsStat::class);
        $this->stats = $arr;

        return $this;
    }

}

