<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * server provided client configuration
 *
 * Generated from protobuf message <code>livekit.ClientConfiguration</code>
 */
class ClientConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration video = 1;</code>
     */
    protected $video = null;
    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration screen = 2;</code>
     */
    protected $screen = null;
    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting resume_connection = 3;</code>
     */
    protected $resume_connection = 0;
    /**
     * Generated from protobuf field <code>.livekit.DisabledCodecs disabled_codecs = 4;</code>
     */
    protected $disabled_codecs = null;
    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting force_relay = 5;</code>
     */
    protected $force_relay = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\VideoConfiguration $video
     *     @type \Livekit\VideoConfiguration $screen
     *     @type int $resume_connection
     *     @type \Livekit\DisabledCodecs $disabled_codecs
     *     @type int $force_relay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration video = 1;</code>
     * @return \Livekit\VideoConfiguration|null
     */
    public function getVideo()
    {
        return $this->video;
    }

    public function hasVideo()
    {
        return isset($this->video);
    }

    public function clearVideo()
    {
        unset($this->video);
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration video = 1;</code>
     * @param \Livekit\VideoConfiguration $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \Livekit\VideoConfiguration::class);
        $this->video = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration screen = 2;</code>
     * @return \Livekit\VideoConfiguration|null
     */
    public function getScreen()
    {
        return $this->screen;
    }

    public function hasScreen()
    {
        return isset($this->screen);
    }

    public function clearScreen()
    {
        unset($this->screen);
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoConfiguration screen = 2;</code>
     * @param \Livekit\VideoConfiguration $var
     * @return $this
     */
    public function setScreen($var)
    {
        GPBUtil::checkMessage($var, \Livekit\VideoConfiguration::class);
        $this->screen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting resume_connection = 3;</code>
     * @return int
     */
    public function getResumeConnection()
    {
        return $this->resume_connection;
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting resume_connection = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResumeConnection($var)
    {
        GPBUtil::checkEnum($var, \Livekit\ClientConfigSetting::class);
        $this->resume_connection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DisabledCodecs disabled_codecs = 4;</code>
     * @return \Livekit\DisabledCodecs|null
     */
    public function getDisabledCodecs()
    {
        return $this->disabled_codecs;
    }

    public function hasDisabledCodecs()
    {
        return isset($this->disabled_codecs);
    }

    public function clearDisabledCodecs()
    {
        unset($this->disabled_codecs);
    }

    /**
     * Generated from protobuf field <code>.livekit.DisabledCodecs disabled_codecs = 4;</code>
     * @param \Livekit\DisabledCodecs $var
     * @return $this
     */
    public function setDisabledCodecs($var)
    {
        GPBUtil::checkMessage($var, \Livekit\DisabledCodecs::class);
        $this->disabled_codecs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting force_relay = 5;</code>
     * @return int
     */
    public function getForceRelay()
    {
        return $this->force_relay;
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting force_relay = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setForceRelay($var)
    {
        GPBUtil::checkEnum($var, \Livekit\ClientConfigSetting::class);
        $this->force_relay = $var;

        return $this;
    }

}

