<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.Codec</code>
 */
class Codec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mime = 1;</code>
     */
    protected $mime = '';
    /**
     * Generated from protobuf field <code>string fmtp_line = 2;</code>
     */
    protected $fmtp_line = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mime
     *     @type string $fmtp_line
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mime = 1;</code>
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Generated from protobuf field <code>string mime = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMime($var)
    {
        GPBUtil::checkString($var, True);
        $this->mime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fmtp_line = 2;</code>
     * @return string
     */
    public function getFmtpLine()
    {
        return $this->fmtp_line;
    }

    /**
     * Generated from protobuf field <code>string fmtp_line = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFmtpLine($var)
    {
        GPBUtil::checkString($var, True);
        $this->fmtp_line = $var;

        return $this;
    }

}

