<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\DataStream\Trailer instead.
     * @deprecated
     */
    class DataStream_Trailer {}
}
class_exists(DataStream\Trailer::class);
@trigger_error('Livekit\DataStream_Trailer is deprecated and will be removed in the next major release. Use Livekit\DataStream\Trailer instead', E_USER_DEPRECATED);

