<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_dispatch.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.DeleteAgentDispatchRequest</code>
 */
class DeleteAgentDispatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dispatch_id = 1 [(.logger.name) = "dispatchID"];</code>
     */
    protected $dispatch_id = '';
    /**
     * Generated from protobuf field <code>string room = 2;</code>
     */
    protected $room = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dispatch_id
     *     @type string $room
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAgentDispatch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dispatch_id = 1 [(.logger.name) = "dispatchID"];</code>
     * @return string
     */
    public function getDispatchId()
    {
        return $this->dispatch_id;
    }

    /**
     * Generated from protobuf field <code>string dispatch_id = 1 [(.logger.name) = "dispatchID"];</code>
     * @param string $var
     * @return $this
     */
    public function setDispatchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dispatch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room = 2;</code>
     * @return string
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Generated from protobuf field <code>string room = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkString($var, True);
        $this->room = $var;

        return $this;
    }

}

