<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_connector_whatsapp.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\DisconnectWhatsAppCallRequest\DisconnectReason instead.
     * @deprecated
     */
    class DisconnectWhatsAppCallRequest_DisconnectReason {}
}
class_exists(DisconnectWhatsAppCallRequest\DisconnectReason::class);
@trigger_error('Livekit\DisconnectWhatsAppCallRequest_DisconnectReason is deprecated and will be removed in the next major release. Use Livekit\DisconnectWhatsAppCallRequest\DisconnectReason instead', E_USER_DEPRECATED);

