<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_internal.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.ICEConfig</code>
 */
class ICEConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_subscriber = 1;</code>
     */
    protected $preference_subscriber = 0;
    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_publisher = 2;</code>
     */
    protected $preference_publisher = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $preference_subscriber
     *     @type int $preference_publisher
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitInternal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_subscriber = 1;</code>
     * @return int
     */
    public function getPreferenceSubscriber()
    {
        return $this->preference_subscriber;
    }

    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_subscriber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPreferenceSubscriber($var)
    {
        GPBUtil::checkEnum($var, \Livekit\ICECandidateType::class);
        $this->preference_subscriber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_publisher = 2;</code>
     * @return int
     */
    public function getPreferencePublisher()
    {
        return $this->preference_publisher;
    }

    /**
     * Generated from protobuf field <code>.livekit.ICECandidateType preference_publisher = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPreferencePublisher($var)
    {
        GPBUtil::checkEnum($var, \Livekit\ICECandidateType::class);
        $this->preference_publisher = $var;

        return $this;
    }

}

