<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_phone_number.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListPhoneNumbersResponse - Response containing phone numbers
 *
 * Generated from protobuf message <code>livekit.ListPhoneNumbersResponse</code>
 */
class ListPhoneNumbersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * List of phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber items = 1;</code>
     */
    private $items;
    /**
     * Token for next page (empty if no more pages)
     *
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     */
    protected $next_page_token = null;
    /**
     * Total number of phone numbers
     *
     * Generated from protobuf field <code>int32 total_count = 3;</code>
     */
    protected $total_count = 0;
    /**
     * Total number of offline phone numbers
     *
     * Generated from protobuf field <code>int32 offline_count = 4;</code>
     */
    protected $offline_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $items
     *           List of phone numbers
     *     @type \Livekit\TokenPagination $next_page_token
     *           Token for next page (empty if no more pages)
     *     @type int $total_count
     *           Total number of phone numbers
     *     @type int $offline_count
     *           Total number of offline phone numbers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitPhoneNumber::initOnce();
        parent::__construct($data);
    }

    /**
     * List of phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * List of phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber items = 1;</code>
     * @param \Livekit\PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\PhoneNumber::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Token for next page (empty if no more pages)
     *
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     * @return \Livekit\TokenPagination|null
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    public function hasNextPageToken()
    {
        return isset($this->next_page_token);
    }

    public function clearNextPageToken()
    {
        unset($this->next_page_token);
    }

    /**
     * Token for next page (empty if no more pages)
     *
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     * @param \Livekit\TokenPagination $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkMessage($var, \Livekit\TokenPagination::class);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * Total number of phone numbers
     *
     * Generated from protobuf field <code>int32 total_count = 3;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Total number of phone numbers
     *
     * Generated from protobuf field <code>int32 total_count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_count = $var;

        return $this;
    }

    /**
     * Total number of offline phone numbers
     *
     * Generated from protobuf field <code>int32 offline_count = 4;</code>
     * @return int
     */
    public function getOfflineCount()
    {
        return $this->offline_count;
    }

    /**
     * Total number of offline phone numbers
     *
     * Generated from protobuf field <code>int32 offline_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOfflineCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->offline_count = $var;

        return $this;
    }

}

