<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_rtc.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.ParticipantUpdate</code>
 */
class ParticipantUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     */
    private $participants;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Livekit\ParticipantInfo>|\Google\Protobuf\Internal\RepeatedField $participants
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParticipants()
    {
        return $this->participants;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     * @param array<\Livekit\ParticipantInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParticipants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\ParticipantInfo::class);
        $this->participants = $arr;

        return $this;
    }

}

