<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_room.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.PerformRpcRequest</code>
 */
class PerformRpcRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string room = 1;</code>
     */
    protected $room = '';
    /**
     * Generated from protobuf field <code>string destination_identity = 2;</code>
     */
    protected $destination_identity = '';
    /**
     * Generated from protobuf field <code>string method = 3;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>string payload = 4;</code>
     */
    protected $payload = '';
    /**
     * Generated from protobuf field <code>uint32 response_timeout_ms = 5;</code>
     */
    protected $response_timeout_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $room
     *     @type string $destination_identity
     *     @type string $method
     *     @type string $payload
     *     @type int $response_timeout_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitRoom::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string room = 1;</code>
     * @return string
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Generated from protobuf field <code>string room = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkString($var, True);
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string destination_identity = 2;</code>
     * @return string
     */
    public function getDestinationIdentity()
    {
        return $this->destination_identity;
    }

    /**
     * Generated from protobuf field <code>string destination_identity = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 3;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payload = 4;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>string payload = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 response_timeout_ms = 5;</code>
     * @return int
     */
    public function getResponseTimeoutMs()
    {
        return $this->response_timeout_ms;
    }

    /**
     * Generated from protobuf field <code>uint32 response_timeout_ms = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseTimeoutMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->response_timeout_ms = $var;

        return $this;
    }

}

