<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT! (protoc-gen-twirp_php 0.15.0)
# source: livekit_phone_number.proto

declare(strict_types=1);

namespace Livekit;

/**
 * Public Phone Number Service - External API for phone number management
 *
 * Generated from protobuf service <code>livekit.PhoneNumberService</code>
 */
interface PhoneNumberService
{
    /**
     * Search available phone numbers in inventory
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/SearchPhoneNumbers</code>
     *
     * @throws \Twirp\Error
     */
    public function SearchPhoneNumbers(array $ctx, \Livekit\SearchPhoneNumbersRequest $req): \Livekit\SearchPhoneNumbersResponse;

    /**
     * Purchase a phone number from inventory
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/PurchasePhoneNumber</code>
     *
     * @throws \Twirp\Error
     */
    public function PurchasePhoneNumber(array $ctx, \Livekit\PurchasePhoneNumberRequest $req): \Livekit\PurchasePhoneNumberResponse;

    /**
     * List phone numbers for a project
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/ListPhoneNumbers</code>
     *
     * @throws \Twirp\Error
     */
    public function ListPhoneNumbers(array $ctx, \Livekit\ListPhoneNumbersRequest $req): \Livekit\ListPhoneNumbersResponse;

    /**
     * Get a phone number from a project
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/GetPhoneNumber</code>
     *
     * @throws \Twirp\Error
     */
    public function GetPhoneNumber(array $ctx, \Livekit\GetPhoneNumberRequest $req): \Livekit\GetPhoneNumberResponse;

    /**
     * Update a phone number in a project
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/UpdatePhoneNumber</code>
     *
     * @throws \Twirp\Error
     */
    public function UpdatePhoneNumber(array $ctx, \Livekit\UpdatePhoneNumberRequest $req): \Livekit\UpdatePhoneNumberResponse;

    /**
     * Release phone numbers
     *
     * Generated from protobuf method <code>livekit.PhoneNumberService/ReleasePhoneNumbers</code>
     *
     * @throws \Twirp\Error
     */
    public function ReleasePhoneNumbers(array $ctx, \Livekit\ReleasePhoneNumbersRequest $req): \Livekit\ReleasePhoneNumbersResponse;
}
