<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_phone_number.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PurchasePhoneNumberResponse - Response containing the purchased phone numbers
 *
 * Generated from protobuf message <code>livekit.PurchasePhoneNumberResponse</code>
 */
class PurchasePhoneNumberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Details of the purchased phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber phone_numbers = 1;</code>
     */
    private $phone_numbers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $phone_numbers
     *           Details of the purchased phone numbers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitPhoneNumber::initOnce();
        parent::__construct($data);
    }

    /**
     * Details of the purchased phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber phone_numbers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhoneNumbers()
    {
        return $this->phone_numbers;
    }

    /**
     * Details of the purchased phone numbers
     *
     * Generated from protobuf field <code>repeated .livekit.PhoneNumber phone_numbers = 1;</code>
     * @param \Livekit\PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhoneNumbers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\PhoneNumber::class);
        $this->phone_numbers = $arr;

        return $this;
    }

}

