<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_recording.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.RtmpOutput</code>
 */
class RtmpOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     */
    private $urls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $urls
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitRecording::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUrls()
    {
        return $this->urls;
    }

    /**
     * Generated from protobuf field <code>repeated string urls = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->urls = $arr;

        return $this;
    }

}

