<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\Scenario\Delete\Request instead.
     * @deprecated
     */
    class Scenario_Delete_Request {}
}
class_exists(Scenario\Delete\Request::class);
@trigger_error('Livekit\Scenario_Delete_Request is deprecated and will be removed in the next major release. Use Livekit\Scenario\Delete\Request instead', E_USER_DEPRECATED);

