<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\Scenario\CreateFromSession\Request instead.
     * @deprecated
     */
    class Scenario_CreateFromSession_Request {}
}
class_exists(Scenario\CreateFromSession\Request::class);
@trigger_error('Livekit\Scenario_CreateFromSession_Request is deprecated and will be removed in the next major release. Use Livekit\Scenario\CreateFromSession\Request instead', E_USER_DEPRECATED);

