<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\Scenario\CreateFromSession instead.
     * @deprecated
     */
    class Scenario_CreateFromSession {}
}
class_exists(Scenario\CreateFromSession::class);
@trigger_error('Livekit\Scenario_CreateFromSession is deprecated and will be removed in the next major release. Use Livekit\Scenario\CreateFromSession instead', E_USER_DEPRECATED);

