<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\Scenario\Create instead.
     * @deprecated
     */
    class Scenario_Create {}
}
class_exists(Scenario\Create::class);
@trigger_error('Livekit\Scenario_Create is deprecated and will be removed in the next major release. Use Livekit\Scenario\Create instead', E_USER_DEPRECATED);

