<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\Scenario\PBList instead.
     * @deprecated
     */
    class Scenario_List {}
}
class_exists(Scenario\PBList::class);
@trigger_error('Livekit\Scenario_List is deprecated and will be removed in the next major release. Use Livekit\Scenario\PBList instead', E_USER_DEPRECATED);

