<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\ServerInfo\Edition instead.
     * @deprecated
     */
    class ServerInfo_Edition {}
}
class_exists(ServerInfo\Edition::class);
@trigger_error('Livekit\ServerInfo_Edition is deprecated and will be removed in the next major release. Use Livekit\ServerInfo\Edition instead', E_USER_DEPRECATED);

