<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\ConfirmSourceUpload\Response instead.
     * @deprecated
     */
    class SimulationRun_ConfirmSourceUpload_Response {}
}
class_exists(SimulationRun\ConfirmSourceUpload\Response::class);
@trigger_error('Livekit\SimulationRun_ConfirmSourceUpload_Response is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\ConfirmSourceUpload\Response instead', E_USER_DEPRECATED);

