<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\Get\Request instead.
     * @deprecated
     */
    class SimulationRun_Get_Request {}
}
class_exists(SimulationRun\Get\Request::class);
@trigger_error('Livekit\SimulationRun_Get_Request is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\Get\Request instead', E_USER_DEPRECATED);

