<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\Create\Scenario instead.
     * @deprecated
     */
    class SimulationRun_Create_Scenario {}
}
class_exists(SimulationRun\Create\Scenario::class);
@trigger_error('Livekit\SimulationRun_Create_Scenario is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\Create\Scenario instead', E_USER_DEPRECATED);

