<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\Job\Status instead.
     * @deprecated
     */
    class SimulationRun_Job_Status {}
}
class_exists(SimulationRun\Job\Status::class);
@trigger_error('Livekit\SimulationRun_Job_Status is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\Job\Status instead', E_USER_DEPRECATED);

