<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\ConfirmSourceUpload instead.
     * @deprecated
     */
    class SimulationRun_ConfirmSourceUpload {}
}
class_exists(SimulationRun\ConfirmSourceUpload::class);
@trigger_error('Livekit\SimulationRun_ConfirmSourceUpload is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\ConfirmSourceUpload instead', E_USER_DEPRECATED);

