<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_sip.proto

namespace Livekit;

use UnexpectedValueException;

/**
 * Protobuf type <code>livekit.SIPTransport</code>
 */
class SIPTransport
{
    /**
     * Generated from protobuf enum <code>SIP_TRANSPORT_AUTO = 0;</code>
     */
    const SIP_TRANSPORT_AUTO = 0;
    /**
     * Generated from protobuf enum <code>SIP_TRANSPORT_UDP = 1;</code>
     */
    const SIP_TRANSPORT_UDP = 1;
    /**
     * Generated from protobuf enum <code>SIP_TRANSPORT_TCP = 2;</code>
     */
    const SIP_TRANSPORT_TCP = 2;
    /**
     * Generated from protobuf enum <code>SIP_TRANSPORT_TLS = 3;</code>
     */
    const SIP_TRANSPORT_TLS = 3;

    private static $valueToName = [
        self::SIP_TRANSPORT_AUTO => 'SIP_TRANSPORT_AUTO',
        self::SIP_TRANSPORT_UDP => 'SIP_TRANSPORT_UDP',
        self::SIP_TRANSPORT_TCP => 'SIP_TRANSPORT_TCP',
        self::SIP_TRANSPORT_TLS => 'SIP_TRANSPORT_TLS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

