<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_rtc.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.SyncState</code>
 */
class SyncState extends \Google\Protobuf\Internal\Message
{
    /**
     * last subscribe answer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     */
    protected $answer = null;
    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     */
    protected $subscription = null;
    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     */
    private $publish_tracks;
    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     */
    private $data_channels;
    /**
     * last received server side offer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     */
    protected $offer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\SessionDescription $answer
     *           last subscribe answer before reconnecting
     *     @type \Livekit\UpdateSubscription $subscription
     *     @type array<\Livekit\TrackPublishedResponse>|\Google\Protobuf\Internal\RepeatedField $publish_tracks
     *     @type array<\Livekit\DataChannelInfo>|\Google\Protobuf\Internal\RepeatedField $data_channels
     *     @type \Livekit\SessionDescription $offer
     *           last received server side offer before reconnecting
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * last subscribe answer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     * @return \Livekit\SessionDescription|null
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    public function hasAnswer()
    {
        return isset($this->answer);
    }

    public function clearAnswer()
    {
        unset($this->answer);
    }

    /**
     * last subscribe answer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     * @param \Livekit\SessionDescription $var
     * @return $this
     */
    public function setAnswer($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SessionDescription::class);
        $this->answer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     * @return \Livekit\UpdateSubscription|null
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    public function hasSubscription()
    {
        return isset($this->subscription);
    }

    public function clearSubscription()
    {
        unset($this->subscription);
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     * @param \Livekit\UpdateSubscription $var
     * @return $this
     */
    public function setSubscription($var)
    {
        GPBUtil::checkMessage($var, \Livekit\UpdateSubscription::class);
        $this->subscription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublishTracks()
    {
        return $this->publish_tracks;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     * @param array<\Livekit\TrackPublishedResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublishTracks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\TrackPublishedResponse::class);
        $this->publish_tracks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDataChannels()
    {
        return $this->data_channels;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     * @param array<\Livekit\DataChannelInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDataChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\DataChannelInfo::class);
        $this->data_channels = $arr;

        return $this;
    }

    /**
     * last received server side offer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     * @return \Livekit\SessionDescription|null
     */
    public function getOffer()
    {
        return $this->offer;
    }

    public function hasOffer()
    {
        return isset($this->offer);
    }

    public function clearOffer()
    {
        unset($this->offer);
    }

    /**
     * last received server side offer before reconnecting
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     * @param \Livekit\SessionDescription $var
     * @return $this
     */
    public function setOffer($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SessionDescription::class);
        $this->offer = $var;

        return $this;
    }

}

