<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

/**
 * Protobuf type <code>livekit.TrackSource</code>
 */
class TrackSource
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>CAMERA = 1;</code>
     */
    const CAMERA = 1;
    /**
     * Generated from protobuf enum <code>MICROPHONE = 2;</code>
     */
    const MICROPHONE = 2;
    /**
     * Generated from protobuf enum <code>SCREEN_SHARE = 3;</code>
     */
    const SCREEN_SHARE = 3;
    /**
     * Generated from protobuf enum <code>SCREEN_SHARE_AUDIO = 4;</code>
     */
    const SCREEN_SHARE_AUDIO = 4;
}

