<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

/**
 * Protobuf type <code>livekit.TrackType</code>
 */
class TrackType
{
    /**
     * Generated from protobuf enum <code>AUDIO = 0;</code>
     */
    const AUDIO = 0;
    /**
     * Generated from protobuf enum <code>VIDEO = 1;</code>
     */
    const VIDEO = 1;
    /**
     * Generated from protobuf enum <code>DATA = 2;</code>
     */
    const DATA = 2;
}

