<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_rtc.proto

namespace Livekit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.UpdateSubscription</code>
 */
class UpdateSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string track_sids = 1;</code>
     */
    private $track_sids;
    /**
     * Generated from protobuf field <code>bool subscribe = 2;</code>
     */
    protected $subscribe = false;
    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantTracks participant_tracks = 3;</code>
     */
    private $participant_tracks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $track_sids
     *     @type bool $subscribe
     *     @type array<\Livekit\ParticipantTracks>|\Google\Protobuf\Internal\RepeatedField $participant_tracks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string track_sids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrackSids()
    {
        return $this->track_sids;
    }

    /**
     * Generated from protobuf field <code>repeated string track_sids = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrackSids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->track_sids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool subscribe = 2;</code>
     * @return bool
     */
    public function getSubscribe()
    {
        return $this->subscribe;
    }

    /**
     * Generated from protobuf field <code>bool subscribe = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSubscribe($var)
    {
        GPBUtil::checkBool($var);
        $this->subscribe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantTracks participant_tracks = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParticipantTracks()
    {
        return $this->participant_tracks;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantTracks participant_tracks = 3;</code>
     * @param array<\Livekit\ParticipantTracks>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParticipantTracks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Livekit\ParticipantTracks::class);
        $this->participant_tracks = $arr;

        return $this;
    }

}

