<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent.proto

namespace Livekit;

use UnexpectedValueException;

/**
 * Protobuf type <code>livekit.WorkerStatus</code>
 */
class WorkerStatus
{
    /**
     * Generated from protobuf enum <code>WS_AVAILABLE = 0;</code>
     */
    const WS_AVAILABLE = 0;
    /**
     * Generated from protobuf enum <code>WS_FULL = 1;</code>
     */
    const WS_FULL = 1;

    private static $valueToName = [
        self::WS_AVAILABLE => 'WS_AVAILABLE',
        self::WS_FULL => 'WS_FULL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

