<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit\ScenarioGroup\Create;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.ScenarioGroup.Create.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.ScenarioGroup scenario_group = 1;</code>
     */
    protected $scenario_group = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Livekit\ScenarioGroup $scenario_group
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAgentSimulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.ScenarioGroup scenario_group = 1;</code>
     * @return \Livekit\ScenarioGroup|null
     */
    public function getScenarioGroup()
    {
        return $this->scenario_group;
    }

    public function hasScenarioGroup()
    {
        return isset($this->scenario_group);
    }

    public function clearScenarioGroup()
    {
        unset($this->scenario_group);
    }

    /**
     * Generated from protobuf field <code>.livekit.ScenarioGroup scenario_group = 1;</code>
     * @param \Livekit\ScenarioGroup $var
     * @return $this
     */
    public function setScenarioGroup($var)
    {
        GPBUtil::checkMessage($var, \Livekit\ScenarioGroup::class);
        $this->scenario_group = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Response::class, \Livekit\ScenarioGroup_Create_Response::class);

