<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger/options.proto

namespace GPBMetadata\Logger;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
v
logger/options.protologger google/protobuf/descriptor.protoB,Z*github.com/livekit/protocol/livekit/loggerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

