<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit\ServerInfo;

use UnexpectedValueException;

/**
 * Protobuf type <code>livekit.ServerInfo.Edition</code>
 */
class Edition
{
    /**
     * Generated from protobuf enum <code>Standard = 0;</code>
     */
    const Standard = 0;
    /**
     * Generated from protobuf enum <code>Cloud = 1;</code>
     */
    const Cloud = 1;

    private static $valueToName = [
        self::Standard => 'Standard',
        self::Cloud => 'Cloud',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Edition::class, \Livekit\ServerInfo_Edition::class);

