<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit\DataPacket;

use UnexpectedValueException;

/**
 * Protobuf type <code>livekit.DataPacket.Kind</code>
 */
class Kind
{
    /**
     * Generated from protobuf enum <code>RELIABLE = 0;</code>
     */
    const RELIABLE = 0;
    /**
     * Generated from protobuf enum <code>LOSSY = 1;</code>
     */
    const LOSSY = 1;

    private static $valueToName = [
        self::RELIABLE => 'RELIABLE',
        self::LOSSY => 'LOSSY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Kind::class, \Livekit\DataPacket_Kind::class);

